#playbook install docker on ubuntu 20.04
- name: install docker
  hosts: all
  tasks:
    - name: install apt repository
      apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        state: present
      register: out
      become: true
    - debug:
        var: out

    #- name: add GPG key
      #apt_key:
