#playbook install docker on ubuntu 20.04
- name: install docker
  hosts: all
  tasks:
    - name: install apt repository
      apt:
        pkg:
        - ca-certificates
        - curl
        - gnupg
        state: present
      register: out
      become: true
    - debug:
        var: out

    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: add apt repository
      apt_repository:
        repo: https://download.docker.com/linux/ubuntu stable
        state: present
      register: out
      become: true
    - debug:
        var: out

    - name: install docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: present
      register: out
      become: true
    - debug:
        var: out
