#playbook install postgresql on ubuntu 20.04
- name: install postgresql
  hosts: study
  tasks:
    - name: install postgre
      block:
        - name: apt install postgresql
          apt:
            pkg:
             - postgresql
             - postgresql-contrib
            update_cache: yes
            state: latest
        - name: start service postgresql
          service:
            name: postgresql
            state: started
        - name: Grant ansible to postgreserver
          postgresql_pg_hba:
            dest: /var/lib/postgres/data/pg_hba.conf
            contype: host
            databases: all
            users: postgres
            method: md5
            create: true
        - name: Create a new database with name "app"
          postgresql_db:
            name: app
        - name: Create user in postgre
          postgresql_user:
            db: app
            name: app_user
            password: 123
            priv: ALL
        - name: added access local to db
          postgresql_pg_hba:
            dest: /var/lib/postgres/data/pg_hba.conf
            contype: local
            users: app_user
            databases: app
      become: yes
