#LEMP
- name: install lemp stack
  hosts: all
  become: true
  roles:
    - nginx_for_lemp
    - mysql_for_lemp
    - php_for_lemp

  tasks:
  - name: reload nginx_for_lemp
    ansible.builtin.service:
      name: nginx_for_lemp
      state: reloaded

