- src: git@gitlab.alkudr.ru/roles/node16.git
  scm: git
  version: master

- src: git@gitlab.alkudr.ru/roles/game2048-docker.git
  scm: git
  version: master

- src: git@gitlab.alkudr.ru/roles/docker.git
  scm: git
  version: master