- name: install mysql
  ansible.builtin.apt:
    pkg: 'mysql-server'
    state: latest

- name: install pymysql
  ansible.builtin.apt:
    pkg: 'python3-pymysql'
    state: latest

- name: setup root user
  community.mysql.mysql_user:
    name: root
    password: 123
    login_user: root
    login_password: 123
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: remove anonymous users
  community.mysql.mysql_user:
    name: ""
    state: absent
    login_user: root
    login_password: 123

- name: remove test database
  community.mysql.mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: 123
